const p4_to_applicant = {
  director_contact_first_name: "John",
  director_contact_last_name: "Doe",
  director_contact_title: "Director",
  adjutant_contact_form_of_address: "Major General",
  adjutant_contact_first_name: "Paul",
  adjutant_contact_last_name: "Smith",
  adjutant_contact_title: "The Adjudant General",
  current_date: "May 15, 2021",
  disaster_number: "1909",
  fips_number: "123456",
  applicant_legal_name: "City of Waverly",
  applicant_agent_form_of_adddress: "The Honorable",
  applicant_agent_first_name: "Shirley",
  applicant_agent_last_name: "Jackson",
  applicant_agent_title: "Director",
  applicant_mailing_line_1: "46 Main Street East",
  applicant_mailing_city: "Knoxville",
  applicant_mailing_state: "Tennessee",
  applicant_mailing_zip_code: "37901",
  applicant_agent_name_prefix: "Prefix",
  pa_liaison_contact_first_name: "Laura",
  pa_liaison_contact_last_name: "Carter",
  pa_liaison_contact_phone_business: "(425) 555-0123",
  pa_liaison_contact_email: "lcarter@gmail.com",
  program_manager_first_name: "David",
  program_manager_last_name: "Roberts",
  program_manager_title: "Regional Manager",
  program_manager_initials: "D.R.",
  pa_liaison_contact_initials: "L.R.",
  applicant_county: "Knox County",
  tema_region: "East Region",
};

export default p4_to_applicant;
